config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

    root 'pets#index'
    
  scope '/admin' do
      resources :users do
            collection do
                get 'login'
                post 'auth'
                get 'logout'
            end 
      end #end users
      
  end #end scope admin
    
  namespace :admin do
      resources :pets do
            collection do
                get 'batch_upload'
                post 'do_batch_upload'
                get 'refine_data'
                post 'form_search', :defaults => { :format => 'json' }
            end 
      end#end pets
  end
    
    
  resources :posts, :except => [:index] do
  end
    
  resources :pets, :except => [:show] do
      collection do
        post 'search', :defaults => { :format => 'json' }
      end
  end
    
  resources :pets, :except => [:index], :only => [:show], param: :number do 
  end
  
    
  resources :rankings, :except => [:show, :new, :create] do
      collection do
          post 'visitor_create/:pet_id' => 'rankings#visitor_create', as: :visitor_create
          get 'update_all_pets_rankings'
      end
  end
    
  

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, uniqueness: true, length: { in: 1..18 }
    validates :login, uniqueness: true, length: { in: 4..30 }
    validates :password, length: { in: 5..30 }
    self.per_page = 2
    
    def is_admin?
        login == "admin"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
   # layout "backend_users_login", only: [:login]
    layout "backend", except: [:login, :auth, :logout]
    before_action :authenticate_user, except: [:login, :auth, :logout]
    def index
        @users = User.all.paginate(:page => params[:page])
    end
    
    def login
        if has_login? 
            redirect_to users_path
            return
        end
        
        if session[:invalid_id_or_password]
            session.delete(:invalid_id_or_password)
            @box_class  = "shake"
        end
        render :layout => 'backend_users_login'
    end

    def auth
        @users   = User.where("login= ? and password = ?", user_params[:login] , user_params[:password])
        
        if @users.count>0
            session[:user_id] = @users.first.id
            update_admin_session_expires_time
            redirect_to users_path
        else 
            flash[:error] = "Invalid login or password, please try again."
            session[:invalid_id_or_password] = true
            redirect_to login_users_path()
        end
    
    end
    
    def logout
        session.delete(:user_id)
        redirect_to login_users_path
    end
    
    def show
        @user   = User.find_by_id(params[:id])
    end
    
    def new
        @user   = User.new
        new_create_vars
    end
    
    def create
        @user   = User.new(user_params)
        if !confirm_is_match_with_password?
            @confirm_not_match   = true
        end
        if @confirm_not_match || !@user.save
            if @confirm_not_match
                add_error_confirm_is_not_match_with_password
            end
            new_create_vars
            render 'new'
        else
            flash[:notice]  = "Create user success!"
            redirect_to @user
        end
    end
    
    def edit
        @user   = User.find_by_id(params[:id])
        edit_update_vars
    end
    
    def update
        @user   = User.find_by_id(params[:id])
        if !confirm_is_match_with_password?
            @confirm_not_match   = true
        end
        if @confirm_not_match || !@user.update(user_params)
            if @confirm_not_match
                add_error_confirm_is_not_match_with_password
            end
            edit_update_vars
            render 'edit'
        else
            flash[:notice]  = "User updated!"
            redirect_to @user
        end
    end#end update
    
    private
    def user_params
        params.require(:user).permit(:login, :password, :name)
    end
    
    def new_create_vars
        @submit_label   = "Create"
        @submit_path    = users_path
        @method         = "post"
    end
    
    def edit_update_vars
        @submit_label   = "Save"
        @submit_path    = user_path(@user)
        @method         = "patch"
    end
    
    def confirm_is_match_with_password?
        params[:user][:confirm_password]==params[:user][:password]
    end
    
    def add_error_confirm_is_not_match_with_password
        @user.errors.add(:confirm_password, "is not match with password.")
    end
    
    def save_user_and_check_error
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<ul class="error_wrapper">
<% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for :user, url: @submit_path, method: @method, :html => {:class => "admin_form"} do |f| %>
<table border="0" cellspacing="0" cellpadding="0" class="form_table">
<tr>
    <td class="label_td">
        Name:
    </td>
    <td class="value_td">
        <%= f.text_field :name, :class => @user.errors.any? && @user.errors[:name].any? ? "error" : "" %>
    </td>
</tr>
<tr>
    <td class="label_td">
        Login:
    </td>
    <td class="value_td">
        <%= f.text_field :login, :class => @user.errors.any? && @user.errors[:login].any? ? "error" : "" %>
    </td>
</tr>
<tr>
    <td class="label_td">
        Password:
    </td>
    <td class="value_td">
        <%= f.password_field :password, :class => @user.errors.any? && @user.errors[:password].any? ? "error" : "" %>
    </td>
</tr>
<tr>
    <td class="label_td">
        Confirm Password:
    </td>
    <td class="value_td">
        <%= f.password_field :confirm_password, :class => @user.errors.any? && @user.errors[:confirm_password].any? ? "error" : "" %>
    </td>
</tr>
<tr>
    <td class="span_td" colspan="2">
            <input class="back gray" type="button" value="Back" onclick="window.location='<%=users_path%>'" />
        <%= f.submit @submit_label, :class => 'create' %>
    </td>
</tr>
<!--<tr>
    <td class="span_td" colspan="2">
        <div class="label_wrapper">
            Password:
        </div>
        <%#= f.text_area :password %>
    </td>
</tr>-->
</table>


<% end %>

app/views/users/edit.html.erb
<h1 class="backend_h1 users_header color">Edit User</h1>

<%= render "users/form" %>

app/views/users/index.html.erb
<h1 class="backend_h1 users_header">Users</h1>

<% if flash[:notice] %>
<ul class="notice_wrapper">
    <li><%=flash[:notice]%></li>
</ul>
<% end %>
<table class="backend_list_table sticky_header">
    <thead>
        <tr>
            <th style="text-align:left;">Login</th>
            <th style="text-align:left;">Password</th>
            <th style="text-align:left;">Last update Date</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr onclick="window.location='<%=user_path(user)%>'">
            <td><%=user.login%></td>
            <td><%=user.password%></td>
            <td><%=user.updated_at%></td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= will_paginate @users %>
<div class="clearer"></div>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
<script>
    sticky_table_init();
</script>

app/views/users/login.html.erb
<div class="login_wrapper">
<div class="login_inner">
    <div class="flash_msg_wrapper">
        <% if flash[:error] %>
        <%=image_tag("admin/users/error_icon.png")%>
        <%=flash[:error]%>
        <% end %>
    </div><!--end flash_msg_wrapper-->
<div class="login_box_wrapper">
    <div class="login_box <%=@box_class%>">
        <div class="login_people"></div>
        <div class="login_label">Login</div>
        <%= form_for :user, url: auth_users_path, :html => {class: 'login_form' }  do |f| %>
        <div class="login_field_wrapper">
            <%= f.text_field :login, placeholder: "login name" %>
        </div>
        <div class="password_field_wrapper">
            <%= f.password_field :password, placeholder: "password" %>
        </div>
        <% end %>
    </div><!--end login_box-->
</div>
</div>
</div>
<script>
    $( document ).ready(function() {
       users_login(); 
    });
</script>

app/views/users/new.html.erb
<h1 class="backend_h1 users_header color">Create User</h1>

<%= render "users/form" %>

app/views/users/show.html.erb
<h1 class="backend_h1 users_header color">User Detail</h1>

<% if flash[:notice] %>
<ul class="notice_wrapper">
    <li><%=flash[:notice]%></li>
</ul>
<% end %>

<table border="0" cellspacing="0" cellpadding="0" class="form_table">
<tr>
    <td class="label_td show">
        Name:
    </td>
    <td class="value_td show">
        <%=@user.name%>
    </td>
</tr>
<tr>
    <td class="label_td show">
        Login:
    </td>
    <td class="value_td show">
        <%=@user.login%>
    </td>
</tr>
<tr>
    <td class="label_td show">
        Password:
    </td>
    <td class="value_td show">
        <%=@user.password%>
    </td>
</tr>
<tr>
    <td class="span_td" colspan="2">
        <input class="back gray" type="button" value="Back" onclick="window.location='<%=users_path%>'" />
        <input class="create" type="button" value="Edit" onclick="window.location='<%=edit_user_path(params[:id])%>'" />
    </td>
</tr>
</table>