config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

    root 'pets#index'
    
  scope '/admin' do
      resources :users do
            collection do
                get 'login'
                post 'auth'
                get 'logout'
            end 
      end #end users
      
  end #end scope admin
    
  namespace :admin do
      resources :pets do
            collection do
                get 'batch_upload'
                post 'do_batch_upload'
                get 'refine_data'
                post 'form_search', :defaults => { :format => 'json' }
            end 
      end#end pets
  end
    
    
  resources :posts, :except => [:index] do
  end
    
  resources :pets, :except => [:show] do
      collection do
        post 'search', :defaults => { :format => 'json' }
      end
  end
    
  resources :pets, :except => [:index], :only => [:show], param: :number do 
  end
  
    
  resources :rankings, :except => [:show, :new, :create] do
      collection do
          post 'visitor_create/:pet_id' => 'rankings#visitor_create', as: :visitor_create
          get 'update_all_pets_rankings'
      end
  end
    
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :authenticate_user#, except: [:index, :show]
    def index
       # @pet = Pet.find_by_id(1387)
      # @pet.calculate_ranking
        
        
        #average_hp   = Ranking.where("pet_id = ?", 1387).average(:hp)
        
        #wow = Ranking.where("pet_id = ? AND ip = ?", 1387, request.remote_ip).count
        
        #render :plain => wow
        #return
        
        
        #@user = User.first
      
      #@ok   = Post.first
      #@ok    = Post.new
      #@ok.title="welcome"
      #@ok.content="nghjio gioj of"
      #@ok.save
      #@ok.user  = @user
      ##
      #render :plain => "yeah"
      #render :plain => @ok.attributes
      @posts = Post.order(:updated_at).all
      @pets = Pet.order("created_at DESC").limit(10)
      
      @left_featured_post           = Post.where(featured: Post.featured_types["Left"]).order(:updated_at).first
      @right_top_featured_post      = Post.where(featured: Post.featured_types["RightTop"]).order(:updated_at).first
      @right_bottom_left_featured_post = Post.where(featured: Post.featured_types["RightBottomLeft"]).order(:updated_at).first
      @right_bottom_right_featured_post = Post.where(featured: Post.featured_types["RightBottomRight"]).order(:updated_at).first
      #render :plain => @left_featured_post.featured == Post.featured_types["Right Top"]
      #render :plain => Post.featured_types["None"]
      #@left_featured_post.featured
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="black-featured">
<div id="black-featured-inner">
    

    <a href="<%=@left_featured_post.nil? ? "" : post_path(@left_featured_post)%>#post-date">
    <div id="left_area">
        <% if !@left_featured_post.nil? %>
        <img src="<%=@left_featured_post.featured_image.url %>" />
        <% end %>
    </div>
    </a>
    <div id="right_area">
<!-- RIGHT TOP-->

        <a href="<%=@right_top_featured_post.nil? ? "" : post_path(@right_top_featured_post)%>#post-date">
        <div id="top_area">
            <% if !@right_top_featured_post.nil? %>
            <img src="<%=@right_top_featured_post.featured_image.url %>" />
            <% end %>

<!-- END RIGHT TOP-->
        </div>
        </a>
        <div id="bottom_area">
<!-- RIGHT BOTTOM LEFT -->

            <a href="<%=@right_bottom_left_featured_post.nil? ? "" : post_path(@right_bottom_left_featured_post)%>#post-date">
            <div id="bottom_left_area">
                <% if !@right_bottom_left_featured_post.nil? %>
                <img src="<%=@right_bottom_left_featured_post.featured_image.url %>" />
                <% end %>

<!-- END RIGHT BOTTOM LEFT-->
            </div>
            </a>
<!-- RIGHT BOTTOM RIGHT -->

            <a href="<%=@right_bottom_right_featured_post.nil? ? "" : post_path(@right_bottom_right_featured_post)%>#post-date">
            <div id="bottom_right_area">
                <% if !@right_bottom_right_featured_post.nil? %>
                <img src="<%=@right_bottom_right_featured_post.featured_image.url %>" />
                <% end %>

<!-- END RIGHT BOTTOM RIGHT-->
            </div>
            </a>
        </div>
    </div>
    <div class="clearer"></div>
</div>
</div><!--end of black-featured-->

<div class="block-area" id="new_posts">
    <div class="header">最新文章</div>
    <ul class="list">

        <% @posts.each do |post| %>
        <a href="<%=post_path(post.id)%>#post-date">
        <li class="post">
            <div class="img-wrapper">
                <img src="<%=post.small_image.url %>" />
            </div>
            <div class="content-wrapper">

                <div class="title">
                    <%=post.title%>
                </div>
                <div class="info">
                    <div class="date-box">
                        <%=post.created_at.strftime("%b.%d")%>
                    </div>
                    <div class="postedby">
                        POSTED BY <%=post.user.name%>
                    </div>
                    <div class="clearer"></div></div>
                <div class="detail">
                    <%=truncate(sanitize(post.content, :tags=>[]), :length => 110, :omission => '...')%>
                </div>
            </div>
            <div class="clearer"></div>
        </li><!--end of post-->
        </a>
        <% end %>
        
        <li class="clearer"></li>

    </ul>
</div><!--end of new_posts-->

<div class="block-area" id="pets">
    <div class="header">棋寵評價</div>
    <ul class="list">
        
        <% @pets.each do |pet| %>
        <a href="<%=pet_path(pet.number)%>#profile">
        <li class="item">
            <div class="img-wrapper">
                <% if pet.circle_image.exists? %>
                <img src="<%=pet.circle_image.url %>" />
                <% else %>
                <div class="circle-cover"></div>
                <%= image_tag "pets/icon/"+get_str_key(pet.number)+".png" %>
                <% end %>
            </div>
            <div class="content-wrapper">
            <div class="content-inner">
                <div class="name">
                    <%=pet.name%>
                </div>
                <div class="rating">
                    <%=pet.ranking_total%>
                </div>
            </div>
            </div>
            <div class="clearer"></div>
        </li>
        </a>
        <% end %>
        
    </ul>
</div><!--end of rating-->

<div class="block-area" id="ads1">
    <div id="ads1-wrapper">
        <div id="ads-example">Ads 1</div>
    </div>
</div><!--end of ads1-->

<div class="clearer"></div>