config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

    root 'pets#index'
    
  scope '/admin' do
      resources :users do
            collection do
                get 'login'
                post 'auth'
                get 'logout'
            end 
      end #end users
      
  end #end scope admin
    
  namespace :admin do
      resources :pets do
            collection do
                get 'batch_upload'
                post 'do_batch_upload'
                get 'refine_data'
                post 'form_search', :defaults => { :format => 'json' }
            end 
      end#end pets
  end
    
    
  resources :posts, :except => [:index] do
  end
    
  resources :pets, :except => [:show] do
      collection do
        post 'search', :defaults => { :format => 'json' }
      end
  end
    
  resources :pets, :except => [:index], :only => [:show], param: :number do 
  end
  
    
  resources :rankings, :except => [:show, :new, :create] do
      collection do
          post 'visitor_create/:pet_id' => 'rankings#visitor_create', as: :visitor_create
          get 'update_all_pets_rankings'
      end
  end
    
  

end

app/models/post.rb
class Post < ActiveRecord::Base
    enum featured_type: {
        None: "1",
        Left: "2",
        RightTop: "3",
        RightBottomLeft: "4",
        RightBottomRight: "5"
  }
    belongs_to :user
    validates :title, length: { in: 1..30 }
    has_attached_file :small_image,
                             styles: { :original => '160x160!' },
                             url: '/system/:class/:attachment/:id_partition/:style/:hash.:extension',
                             path: ':rails_root/public/system/:class/:attachment/:id_partition/:style/:hash.:extension',
                             hash_secret: 'get_from_rake_secret'
    validates_attachment :small_image, content_type: { content_type: /\Aimage\/.*\Z/ },
                                size: { in: 0..1.megabytes }
    
    validates :small_image, presence: true
    
    has_attached_file :featured_image,
                             url: '/system/:class/:attachment/:id_partition/:style/:hash.:extension',
                             path: ':rails_root/public/system/:class/:attachment/:id_partition/:style/:hash.:extension',
                             hash_secret: 'get_from_rake_secret'
    validates_attachment :featured_image, content_type: { content_type: /\Aimage\/.*\Z/ },
                                size: { in: 0..5.megabytes }
    
    validates :featured_image, presence: true, :if => :featured?
    
    def featured?
        featured != Post.featured_types["None"]
    end
    
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout "backend", except: [:index, :show]
    before_action :authenticate_user#, except: [:index, :show]
    
    def index
        #@post = Post.find_by_id(5)
        
        #@post.destroy
        #render :plain =>@post.featured?
        #render :plain =>"ok"
    end
    
    def new
        @post   = Post.new
        new_create_vars
    end
    
    def create
        @post   = Post.new(post_params)
        @post.user  = User.find_by_id(session[:user_id])
        if !@post.save
            new_create_vars
            render 'new'
        else
            flash[:notice]  = "Create post success!"
            redirect_to @post
        end
    end
    
    def show        
        @post   = Post.find_by_id(params[:id])
        if @post.nil?
            redirect_to root_path
            return
        end
        render :layout => 'application'
    end
    
    def edit
        @post   = Post.find_by_id(params[:id])
        if @post.nil?
            redirect_to root_path
            return
        end
        edit_update_vars
    end
    
    def update
        @post   = Post.find_by_id(params[:id])
        if !@post.update(post_params)
            edit_update_vars
            render 'edit'
        else
            flash[:notice]  = "Post updated!"
            redirect_to @post
        end
    end#end update
    
    def destroy
        @post   = Post.find_by_id(params[:id])
        if @post.destroy
            flash[:notice]  = "Post deleted!"
            redirect_to root_path
        else
            edit_update_vars
            render 'edit'
        end
    end
    
    
    private
    def post_params
        params.require(:post).permit(:title, :content, :featured, :small_image, :featured_image)
    end
    
    def new_create_vars
        @submit_label   = "Create"
        @submit_path    = posts_path
        @method         = "post"
    end
    
    def edit_update_vars
        @submit_label   = "Save"
        @submit_path    = post_path(@post)
        @method         = "patch"
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<ul class="error_wrapper">
<% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for :post, url: @submit_path, method: @method, :html => {:class => "admin_form"} do |f| %>
<table border="0" cellspacing="0" cellpadding="0" class="form_table">
<tr>
    <td class="label_td">
        Title:
    </td>
    <td class="value_td">
        <%= f.text_field :title, :class => @post.errors.any? && @post.errors[:title].any? ? "error" : "" %>
    </td>
</tr>
<tr>
    <td class="label_td valign-top">
        Content:
    </td>
    <td class="value_td">
        <%= f.text_area :content, :rows => 10, :class => @post.errors.any? && @post.errors[:content].any? ? "error" : "" %>
    </td>
</tr>

<tr>
    <td class="label_td">
        Featured:
    </td>
    <td class="value_td">
        <%= f.select :featured, options_for_select(Post.featured_types, @post.featured) %>
    </td>
</tr>
    
<tr>
    <td class="label_td <%= @post.small_image.exists? ? 'valign-top' : '' %>">
        Small Image:
    </td>
    <td class="value_td">
        <% if @post.small_image.exists? %>
        <div class="attachment-wrapper">
            <img src="<%=@post.small_image.url() %>" />
        </div>
        <% end %>
        <%= f.file_field :small_image, :class => @post.errors.any? && @post.errors[:small_image].any? ? "error" : "" %>
        <% if @post.small_image.exists? %><div style="height:50px;"></div><% end %>
    </td>
</tr>

<tr>
    <td class="label_td <%= @post.featured_image.exists? ? 'valign-top' : '' %>">
        Featured Image:
    </td>
    <td class="value_td">
        <% if @post.featured_image.exists? %>
        <div class="attachment-wrapper">
            <img src="<%=@post.featured_image.url() %>" />
        </div>
        <% end %>
        <%= f.file_field :featured_image, :class => @post.errors.any? && @post.errors[:featured_image].any? ? "error" : "" %>
    </td>
</tr>
    
<tr>
    <td class="span_td" colspan="2">
            <input class="back gray" type="button" value="Back" onclick="window.location='<%=root_path%>'" />
        <%= f.submit @submit_label, :class => 'create' %>
        
        <% if !@post.new_record? %>
        <%= link_to raw('<input class="delete red" type="button" value="Delete" />'), post_path(@post),
              method: :delete,
              data: { confirm: 'Are you sure?' }, html: :ok %>
        <% end %>
    </td>
</tr>

</table>
<script type="text/javascript">
/* <![CDATA[ */
$(document).ready(function(){
    // your code...
    $("input[type=file]").nicefileinput();
    
});
/* ]]> */

$(document).ready(function() {
    if ($('textarea').length > 0) {
        var data = $('textarea');
        $.each(data, function(i) {
            CKEDITOR.replace(data[i].id);
        });
    }
});
</script>

<% end %>

app/views/posts/edit.html.erb
<h1 class="backend_h1 posts_header color">Edit Post</h1>

<%= render "posts/form" %>

app/views/posts/new.html.erb
<h1 class="backend_h1 posts_header color">Create Post</h1>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<div class="post-outer">
<div class="post-top-banner">
</div>
<div class="post-wrapper">
    <div class="post-date-wrapper" id="post-date">
    <div class="post-date-inner">
        <strong><%=@post.created_at.strftime("%b") %>.</strong><%=@post.created_at.strftime("%d") %>
    </div>
    </div><!--end of post-date-wrapper-->
    
    <div class="title" id="main-content">
        <%=@post.title%>
    </div>
    
    <div class="posted-by">
        Posted by <a href='#'><%=@post.user.name%></a>
    </div>
    
    <div class="post-content-wrapper">
        <%=@post.content.html_safe%>
    </div>
    
    
</div><!--end of post-wrapper-->
</div>

<% if is_admin? %>
<section id="admin-wrap">
    <div id="admin-title">Admin Only</div>
    <div id="admin-inner">
        <input class="create" type="button" value="Edit" onclick="window.location='<%=edit_post_path(params[:id])%>'" />
        <%= link_to raw('<input class="delete red" type="button" value="Delete" />'), post_path(@post),
              method: :delete,
              data: { confirm: 'Are you sure?' }, html: :ok %>
    </div>
</section>
<% end %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_HK/sdk.js#xfbml=1&version=v2.6&appId=997476640336267";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<section id="comment-wrap">
    <div id="comment-inner">
        <div class="fb-comments" data-href="<%=url_for(:only_path => false) %>" data-width="100%" data-numposts="5"></div>
    </div>
</section>